flutter/infra

config/luci-milo.cfg
config/luci-scheduler.cfg

Right now the engine is getting triggered by flutter/flutter instead of flutter/engine
Also adds a short name for the framework.
I'm not 100% sure this will work - partly an experiment here.

fix triggers, give framework short name

---

config/cr-buildbucket.cfg

Property for Cocoapods version and Coveralls-lcov
Will be used by recipe to determine what version of the gem(s) to install.

Versions for ruby gems

---

config/cr-buildbucket.cfg
config/main.star

This is to support a hotfix to flutter stable v1.12.13. Currently changes to the engine recipe since v1.12.13 have broken re-building stable. This change will pin the hotfix builders to use the versions of the framework & engine recipes at the time v1.12.13 was released.
This is not a permanent fix; this change will be reverted after the successful hotfix release. The long-term fix will involve the Flutter team owning the LUCI build recipes.

Update hotfix builders to use hotfix recipes

---

config/generated/flutter/luci/cr-buildbucket.cfg
config/recipes_config.star

This version includes http://crrev.com/c/2247497, which causes the
recipe roller to respect the new `no_cc_authors` recipes.cfg field so it
won't spammily CC authors of rolled recipe changes.

Update recipe-deps-roller CIPD package

---

config/engine_config.star
config/framework_config.star
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-scheduler.cfg
config/main.star
config/packaging_config.star

1. Modified the `BRANCHES` dict to have two refs, `testing-ref` and `release-ref`.
2. Modify the packaging pollers to use `release-ref`, the rest to use `testing-ref`
3. Rename the packaging pollers to have `packaging` in the name, since I was running into lucicfg errors that look like `Error: luci.gitiles_poller("prod/stable-gitiles-trigger-framework") is redeclared, previous declaration:` and I didn't want to refactor further to share the pollers. This could be refactored later.

fix gitiles poller trigger for packaging builders

---

config/engine_config.star
config/generated/flutter/luci/luci-scheduler.cfg

When moving the branch that the gitiles poller watches, it will pick up a LOT of commits. No reason not to set the max_batch_size to 1000 (unless two releases were issued faster than the poller's interval, which seems unlikely). we already batch for packaging.

remove cap to max_batch_size for release builders, defaults to 1000

---

config/generated/flutter/luci/cr-buildbucket.cfg
config/plugins_config.star

Plugins repo is now supporting LUCI pre-submit windows test. But existing recipe is using default `Windows-10`, which fails the `flutter doctor` step: 
```
[X] Visual Studio - develop for Windows
X Visual Studio not installed; this is necessary for Windows development.
```
This PR updates the os to `Windows-Server`, which works: 
https://logs.chromium.org/logs/flutter/led/stuartmorgan_google.com/8262c62e8def8247edb8e1e393a0f00077b60a9555dc8c7259f30762466019fb/+/steps/prepare_environment/0/steps/flutter_doctor/0/stdout
Related issue: 
https://github.com/flutter/flutter/issues/56143#issuecomment-687532941

Update default os to Windows-Server for plugins windows tests

---

config/generated/flutter/luci/cr-buildbucket.cfg
config/plugins_config.star

This is a follow-up of https://github.com/flutter/infra/pull/201.
The default cores for windows builders are 8, however the cores for os `Windows-Server` bot are 32. We need to update to 32 to allow LUCI find corresponding bots.

Update cores to 32 for windows test in Plugins repo

---

config/engine_config.star
config/generated/flutter/luci/commit-queue.cfg
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

Adding new try and prod builder to use the new recipe for running framework test with web engine. (Recipe: https://flutter.googlesource.com/recipes/+/refs/heads/master/recipes/engine/web_engine_framework.py)
Note: I got an error when running lucicfg:
```
luci.builder("try/Linux Web Framework tests") refers to undefined luci.executable("engine/web_engine_framework")
```
please let me know which steps I should take to add the new recipe to recupe_bundles CIPD package (or is it an automated process)
Fixes: https://github.com/flutter/flutter/issues/65052

[web] add new builders to run the new recipe

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

This PR adds corresponding try/prod configs for `deploy_gallery` test.
Related issue: https://github.com/flutter/flutter/issues/66707
Successful runs:
[linux try](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/f02e76edf853f5b9bc72c494f6c4213163d5fe35c2a388e3b95688f4194e1fe2/+/annotations)
[mac try](https://luci-milo.appspot.com/raw/build/logs.chromium.org/flutter/led/keyonghan_google.com/52ad853f8474b32f36e8acf1020fd031f25a1077fdc3880497186bf77e8a0a00/+/annotations)

Add deploy_gallery configs for both try and prod

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

There are no tests in the flutter/flutter repo right now that tests the integration_test packages usage with flutter drive on web. Current driver tests does not cover integration_test package. This created a P0 this week. 
This new builders will use these tests: https://github.com/flutter/flutter/tree/master/dev/integration_tests/web_e2e_tests
Related recipe side code: https://flutter.googlesource.com/recipes/+/6c48adc977b231b55dfeb7937f290c7f610931d2
Related: https://github.com/flutter/flutter/issues/67560

adding web_e2e tests to framework tests

---

config/generated/flutter/luci/cr-buildbucket.cfg
config/plugins_config.star

Windows server bots in luci pool are now all of 8 cores. This PR is to remove the 32 cores dimension requirement to bring the plugins Windows builder back.
Related issue: https://github.com/flutter/flutter/issues/69232

Remove cores dimension for plugins windows builder

---

config/framework_config.star
config/generated/flutter/luci/luci-milo.cfg

Otherwise, it's taking an unfair amount of horizontal space:

Shorten web_long_running_tests -> web_lrt

---

config/framework_config.star
config/generated/flutter/luci/commit-queue.cfg
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

Made `web_tool_tests` shards and its `web` subshard to run on a separate builder.
Web tool tests run frontend server in web mode, invoking ddc as the backend compiler, and uses some SDK API that are not used on other platforms, such as ExpressionCompiler. This change will allow:
- Fast checks of dart SDK CLs against breaking flutter.
- Marking some shards as flaky separately from the rest of tool tests.
See matching changes in flutter:
https://github.com/flutter/flutter/pull/70226

Add web_tool_tests builders

---

config/devicelab_staging_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg
config/lib/common.star

Before migrating devicelab linux tests to prod, we are moving it to staging first to validate effectiveness.
Related issue: https://github.com/flutter/flutter/issues/70648

Add all linux devicelab tests to staging

---

config/devicelab_staging_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/lib/timeout.star

We are running all mac/linux devicelab tests in staging pool, but with 2 bots for each platform. The default 6 hours make it difficult to see whether all tests pass.
This PR increase the expiration_timeout to be 12 hours to have a better visibility.

Increase staging builders expiration_timeout to be 12 hours

---

.vscode/settings.json
config/engine_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg

This is for adding web engine drone builders.
These will be used from the web engine recipe, for sharding (which will eliminate the flakiness happening now on linux web engine) The related design doc: go/web-engine-recipe-drones
related: https://github.com/flutter/flutter/issues/71576

adding web drones which will be called from web engine code

---

config/devicelab_config.star
config/generated/flutter/luci/luci-scheduler.cfg

There are five bots running 45 LUCI devicelab builders.
Current setting `max_concurrent_invocations=3` makes the queue time super high:
Like in the above picture, each builder has three queued builds. This will make the tot builds queuing time even higher if we have continuous more new commits joining. (after finish running a build, it may choose to run an older queued build).
Updating `max_concurrent_invocations` to 1 should have the scheduler always choose newer build to run.
From [quote](https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/lucicfg/doc/README.md#scheduler.policy-args)
> max_concurrent_invocations: limit on a number of builds running at the same time. If the number of currently running builds launched through LUCI Scheduler is more than or equal to …

Change `max_concurrent_invocations` to 1 for luci devicelab builders

---

config/cocoon_config.star
config/generated/flutter/luci/commit-queue.cfg
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg

Cocoon device doctor recipe to build/upload device_doctor package to cipd is ready. This PR adds pre-submit builder configs.
These builders should be triggered whenever any updates from `cocoon/device_doctor`.

Add try builder config for cocoon device doctor

---

config/devicelab_staging_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg
config/lib/common.star

This is to enable devicelab mac-android tests in staging env.
This PR also adds a new category `Mac_android` to distinguish from existing `Mac` category which is mainly for `mac-ios` tests.
Related issue: https://github.com/flutter/flutter/issues/74059

Enable devicelab Mac android tests in staging env

---

config/engine_config.star
config/generated/flutter/luci/cr-buildbucket.cfg

This PR solves https://github.com/flutter/flutter/issues/74642, to avoid timeout of engine Mac builders.

Add mac_model dimension for engine Mac builders to use Macmini8

---

config/devicelab_config.star
config/generated/flutter/luci/cr-buildbucket.cfg

It has been a while since we migrated devicelab Linux and Mac/Android tests to LUCI. 
Over the past month, the max queue time of these builders was ~2.7 hours.
This PR adjusts the expiration_timeout to be 3 hours instead of 12.
Related issue: https://github.com/flutter/flutter/issues/72383

Adjust devicelab linux and mac/android builder expiration_timeout

---

config/devicelab_config.star
config/generated/flutter/luci/luci-milo.cfg

This group linux-android tests together in milo, to separate from host only tests.

Separate devicelab Linux host only tests from Linux-android tests

---

config/devicelab_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

This migrates the last catalina-android test: `smoke_catalina_start_up` to LUCI.
Related: https://github.com/flutter/flutter/issues/74059

Migrate smoke_catalina_start_up to LUCI

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg
config/lib/common.star

This creates separate builder configs for each subshard (Mac and Windows prod ones).
Related: flutter/flutter#77947

Separate SDK Mac and Windows shards into separate builders - prod

---

config/framework_config.star
config/generated/flutter/luci/commit-queue.cfg
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

This is a final step to clean up old consolidated shard builders: separated builders for each shard have been running in both try and prod for Linux, Mac and Windows.
Related issue: https://github.com/flutter/flutter/issues/77947

Remove old consolidated shard builders

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg

The previous PR added the dimension to the linux bots rather than the
mac ones.
Bug: https://github.com/flutter/flutter/issues/81793

Add cores dimension to the correct place.

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg
config/generated/flutter/luci/luci-milo.cfg
config/generated/flutter/luci/luci-notify.cfg
config/generated/flutter/luci/luci-scheduler.cfg

The framework doesn't use "1_3", "2_3", "3_3" any more.

remove old web_long_running_tests shards

---

config/framework_config.star
config/generated/flutter/luci/cr-buildbucket.cfg

Windows tool_integration_tests dependency key has several white spaces
at the end of the string causing the dependency installation to fail.

Fix dependency key.

---

config/cocoon_config.star
config/generated/flutter/luci/commit-queue.cfg

Reverts flutter/infra#456
With https://github.com/flutter/cocoon/pull/1222 - This will be unblocked (we must wait for it be submitted first though)

Revert "Temporarily disable cocoon builders in led recipe tests."

---

config/engine_config.star
config/generated/flutter/luci/cr-buildbucket.cfg

Buildbucket adds a 4m latency by default that adds 4 mins on top of the
execution time. In the flutter use case we would like to pick up the
next available bot if there is no one with the requested caches
immediately.
Bug: https://github.com/flutter/flutter/issues/84295

Override builder cache to remove the 4m latency to get a bot.
